# Generated by Django 3.2.8 on 2021-10-14 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cat',
            old_name='bithdate',
            new_name='birthdate',
        ),
    ]
